[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.10"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
genovault = "9G5ri75FHhrD5V4ujTwvmv5ULCSRTcu4x4mvzKk6tNEb"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm --filter @genovault/sdk test"

[hooks]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
